#!/usr/bin/env python3
"""Chapter 7: generates rtl/crc32_stream.sv. The CRC-32 register update is LINEAR over GF(2): after consuming N data bits, every bit of the new register is the XOR of some bits of the old register and some of the data. This script finds which, by running the bit-serial algorithm SYMBOLICALLY: each register bit is held as a set of variables (c0..c31 old state, d0..d(8k-1) data) represented as an integer bit mask, and the shift and XOR steps of the definition are applied to the masks. The result for k bytes (k = 1..8) is written out as one XOR expression per output bit.
Usage: crc_gen.py [--matrix]   (without arguments, writes rtl/crc32_stream.sv)"""
import os, sys
POLY_R = 0xEDB88320; NVAR_STATE = 32
def symbolic_step(k):
    """Returns 32 masks: bit j of the register after k bytes = XOR of the variables in masks[j]. Variable v < 32 is old state bit v; variable 32 + i is data bit i (data bit 8*b + t is bit t of byte b; byte 0 first)."""
    reg = [1 << j for j in range(32)]
    for b in range(k):
        for t in range(8):
            fb = reg[0] ^ (1 << (32 + 8 * b + t))                      # feedback = register bit 0 XOR the data bit
            reg = reg[1:] + [0]                                         # shift right by one
            for j in range(32):
                if POLY_R >> j & 1: reg[j] ^= fb
    return reg
def terms(mask): return [("c[%d]" % v) if v < 32 else ("d[%d]" % (v - 32)) for v in range(NVAR_STATE + 64) if mask >> v & 1]
def xor_tree(ts):
    """A balanced tree of 4-input XORs written with explicit parentheses, so that a LUT4 mapper sees ceil(log4 n) levels instead of a chain of n - 1 two-input XORs."""
    if len(ts) <= 4: return " ^ ".join(ts)
    g = -(-len(ts) // 4); size = max(4, -(-len(ts) // 4)); parts = [ts[i:i + size] for i in range(0, len(ts), size)]
    return " ^ ".join("(" + xor_tree(p) + ")" if len(p) > 1 else p[0] for p in parts)
def row_weights(k): return [bin(m).count("1") for m in symbolic_step(k)]
def emit():
    o = ["// GENERATED by tools/crc_gen.py -- do not edit. Ethernet CRC-32 (reflected polynomial 0xEDB88320), streaming, W bits per beat (W = 8, 32 or 64).",
         "// crc32_comb: the combinational update. stepK consumes the K low bytes of d (byte 0 in d[7:0]) starting from register state c; the XOR equations come from running the bit-serial algorithm symbolically (see crc_gen.py). k selects the number of valid bytes (1..8; 0 or more than 8 leaves the state unchanged).",
         "// verilator lint_off DECLFILENAME", "// verilator lint_off UNUSEDSIGNAL",
         "module crc32_comb (input logic [31:0] c, input logic [63:0] d, input logic [3:0] k, output logic [31:0] n);"]
    for k in range(1, 9):
        o.append(f"    function logic [31:0] step{k}(input logic [31:0] cc, input logic [63:0] dd);")
        o.append("        begin")
        for j, m in enumerate(symbolic_step(k)): o.append(f"            step{k}[{j}] = " + (xor_tree([t.replace("c[", "cc[").replace("d[", "dd[") for t in terms(m)]) if m else "1'b0") + ";")
        o.append("        end"); o.append("    endfunction")
    o += ["    always_comb begin", "        case (k)", "            4'd1: n = step1(c, d);"] + [f"            4'd{k}: n = step{k}(c, d);" for k in range(2, 9)] + ["            default: n = c;", "        endcase", "    end", "endmodule",
          "// crc32_stream: the frame wrapper. The register starts at all ones; on the last beat of a frame the output is the inverted register (= zlib.crc32 of the frame bytes) one cycle later, and out_good is 1 when it equals the residue 0x2144DF1C (the frame included a correct FCS).",
          "module crc32_stream #(parameter int W = 64) (",
          "    input logic clk, input logic rst, input logic in_valid, input logic [W-1:0] in_data, input logic [3:0] in_nbytes, input logic in_last,",
          "    output logic out_valid, output logic out_good, output logic [31:0] out_crc);",
          "    logic [31:0] st, nx; logic [63:0] d64;",
          "    assign d64 = 64'(in_data);",
          "    crc32_comb u (.c(st), .d(d64), .k(in_nbytes), .n(nx));",
          "    always_ff @(posedge clk) begin",
          "        if (rst) begin st <= 32'hFFFFFFFF; out_valid <= 1'b0; out_good <= 1'b0; out_crc <= 32'd0; end",
          "        else begin",
          "            out_valid <= in_valid && in_last;",
          "            if (in_valid) begin",
          "                if (in_last) begin st <= 32'hFFFFFFFF; out_crc <= ~nx; out_good <= (~nx == 32'h2144DF1C); end",
          "                else st <= nx;",
          "            end",
          "        end", "    end", "endmodule",
          "// crc32_fast: the same function, pipelined for speed (latency 5 instead of 1). The update is LINEAR: new_state = A_k(state) XOR B_k(data). The data part B_k is feed-forward and is computed in its own stages; the feedback loop through the state register is only A_8 (at most 19 inputs per bit) XOR one precomputed word; the partial last beat, which needs A_k for a smaller k, is taken OUT of the loop (the state is captured and the last step is done in a final stage, after which the state restarts).",
          "// Stages: (1) input registers; (2) B_8(d) for full beats and B_k(d) for the last beat, registered; (3) the loop: st <= A_8(st) ^ B_8 for a full beat, snapshot of st and B_k on the last beat, st restarts; (4) x5 = A_k(snapshot) ^ B_k; (5) out_crc = ~x5 and the comparison with the residue.",
          "module crc32_fast #(parameter int W = 64) (",
          "    input logic clk, input logic rst, input logic in_valid, input logic [W-1:0] in_data, input logic [3:0] in_nbytes, input logic in_last,",
          "    output logic out_valid, output logic out_good, output logic [31:0] out_crc);",
          "    localparam logic [3:0] FULL = 4'(W / 8);",
          "    logic [63:0] d1; logic [3:0] nb1; logic last1, v1;                      // stage 1",
          "    logic [31:0] pf, pl_n, pf_n; logic [31:0] pl2, pf2; logic [3:0] nb2; logic last2, v2;  // stage 2",
          "    logic [31:0] st, a_loop, ak, st_s, pl_s, x5; logic [3:0] nb_s; logic last_s, v_s, v5;",
          "    crc32_comb ub_full (.c(32'd0), .d(d1), .k(FULL), .n(pf_n));              // B for a full beat (c = 0 leaves only the data part)",
          "    crc32_comb ub_last (.c(32'd0), .d(d1), .k(nb1), .n(pl_n));              // B for the number of bytes in this beat",
          "    crc32_comb ua_loop (.c(st), .d(64'd0), .k(FULL), .n(a_loop));            // A for a full beat (d = 0 leaves only the state part)",
          "    crc32_comb ua_last (.c(st_s), .d(64'd0), .k(nb_s), .n(ak));",
          "    always_ff @(posedge clk) begin",
          "        if (rst) begin v1 <= 1'b0; v2 <= 1'b0; v_s <= 1'b0; v5 <= 1'b0; st <= 32'hFFFFFFFF; out_valid <= 1'b0; out_good <= 1'b0; out_crc <= 32'd0; end",
          "        else begin",
          "            d1 <= 64'(in_data); nb1 <= in_nbytes; last1 <= in_last; v1 <= in_valid;",
          "            pf2 <= pf_n; pl2 <= pl_n; nb2 <= nb1; last2 <= last1; v2 <= v1;",
          "            v_s <= v2 && last2; nb_s <= nb2; pl_s <= pl2; st_s <= st;",
          "            if (v2) begin if (last2) st <= 32'hFFFFFFFF; else st <= a_loop ^ pf2; end",
          "            v5 <= v_s; x5 <= ak ^ pl_s;",
          "            out_valid <= v5; out_crc <= ~x5; out_good <= (~x5 == 32'h2144DF1C);",
          "        end", "    end", "endmodule"]
    return "\n".join(o) + "\n"
if __name__ == "__main__":
    if "--matrix" in sys.argv:
        for k in (1, 4, 8): w = row_weights(k); print(f"{8 * k:3d} bits per beat: XOR inputs per output bit: min {min(w)}, max {max(w)}, total {sum(w)} terms")
    else:
        root = os.path.dirname(os.path.dirname(os.path.abspath(__file__))); open(os.path.join(root, "rtl", "crc32_stream.sv"), "w").write(emit()); print("wrote rtl/crc32_stream.sv")
