#!/usr/bin/env python3
"""Chapter 16: the parser generator. grammar (model/grammar.py) -> a SystemVerilog module `<name>` that parses MoldUDP64 packets carrying messages of that grammar, one byte per clock.
Usage: python3 tools/gen_parser.py [name] [out.sv] [grammar variable in model/grammar.py]   (defaults: mold_itch rtl/mold_itch.sv ITCH)
The generated module (interface and behaviour are specified by model/itch_gold.py, from the protocol, not from this file):
  in : clk rst valid sop eop data[7:0]            one byte per cycle; sop marks the first byte of a packet (the first byte of the MoldUDP64 header), eop the last
  out: m_valid m_type m_err[1:0] m_idx[15:0] h_seq[63:0] f_<field>...    one message, registered, the cycle after its last byte; err 0 ok, 1 unknown type, 2 length differs from the type's (or is 0); the f_ registers are valid only for err = 0 and the fields the type has
       p_valid p_trunc p_cntbad h_session[79:0] h_count[15:0]            the packet ended (eop), the cycle after the eop byte; trunc: it ended inside the header or inside a block; cntbad: the number of blocks differs from the count (count 0xFFFF, end of session, is not checked)
A new sop abandons a packet in progress, silently. Bytes outside a packet (no sop since the last eop) are ignored."""
import os, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "model"))
import grammar
def gen(g, name="mold_itch"):
    F = grammar.fields(g); types = list(g)
    L = []; A = L.append
    A(f"// GENERATED by tools/gen_parser.py from model/grammar.py -- do not edit. Grammar: {len(types)} message types ({', '.join(types)}), {len(F)} distinct fields.")
    A("// verilator lint_off DECLFILENAME"); A("// verilator lint_off UNUSEDSIGNAL")
    ports = ["input logic clk, input logic rst, input logic valid, input logic sop, input logic eop, input logic [7:0] data,",
             "output logic m_valid, output logic [7:0] m_type, output logic [1:0] m_err, output logic [15:0] m_idx, output logic [63:0] h_seq,"]
    ports.append("output logic p_valid, output logic p_trunc, output logic p_cntbad, output logic [79:0] h_session, output logic [15:0] h_count,")
    fp = [f"output logic [{8 * n - 1}:0] f_{nm}" for nm, n in F.items()]
    A(f"module {name} (\n    " + "\n    ".join(ports) + "\n    " + ",\n    ".join(fp) + ");")
    A("    localparam logic [2:0] IDLE = 3'd0, HDR = 3'd1, LENH = 3'd2, LENL = 3'd3, BODY = 3'd4;")
    A("    logic [2:0] st; logic [4:0] pos; logic [7:0] lenh, off, ty; logic [15:0] rem, nblk; logic [1:0] er, er_d;")
    A("    logic [7:0] exp_len; logic [15:0] len_now; logic last_byte, hdr_last; logic [2:0] st_n; logic [15:0] nblk_n, count_now;")
    A("    always_comb begin")
    A("        case (data)")
    for t, m in g.items(): A(f"            8'h{ord(t):02x}: exp_len = 8'd{grammar.length(m)};   // {t}")
    A("            default: exp_len = 8'd0;"); A("        endcase")
    A("        count_now = (st == HDR) ? {h_count[7:0], data} : h_count;")
    A("        len_now = {lenh, data}; hdr_last = (pos == 5'd19); last_byte = (rem == 16'd1);")
    A("        er_d = (exp_len == 8'd0) ? 2'd1 : (({8'd0, exp_len} == rem) ? 2'd0 : 2'd2);   // at the first body byte rem is the block's length")
    A("        st_n = st; nblk_n = nblk;")
    A("        case (st)")
    A("            HDR:  if (hdr_last) st_n = LENH;")
    A("            LENH: st_n = LENL;")
    A("            LENL: if (len_now == 16'd0) begin st_n = LENH; nblk_n = nblk + 16'd1; end else st_n = BODY;")
    A("            BODY: if (last_byte) begin st_n = LENH; nblk_n = nblk + 16'd1; end")
    A("            default: ;"); A("        endcase")
    A("    end")
    # field select terms
    sel = {nm: [] for nm in F}
    for t, m in g.items():
        o = 1
        for nm, n in m: sel[nm].append((t, o, n)); o += n
    A("    logic " + ", ".join(f"s_{nm}" for nm in F) + ";")
    A("    always_comb begin")
    for nm in F:
        terms = " || ".join(f"(ty == 8'h{ord(t):02x} && off >= 8'd{o} && off < 8'd{o + n})" for t, o, n in sel[nm])
        A(f"        s_{nm} = (st == BODY) && (er == 2'd0) && ({terms});")
    A("    end")
    A("    always_ff @(posedge clk) begin")
    A("        m_valid <= 1'b0; p_valid <= 1'b0;")
    A("        if (rst) st <= IDLE;")
    A("        else if (valid) begin")
    A("            if (sop) begin st <= HDR; pos <= 5'd1; nblk <= 16'd0; h_session <= {72'd0, data}; end")
    A("            else begin")
    A("                st <= st_n; nblk <= nblk_n;")
    A("                case (st)")
    A("                    HDR: begin pos <= pos + 5'd1;")
    A("                        if (pos < 5'd10) h_session <= {h_session[71:0], data}; else if (pos < 5'd18) h_seq <= {h_seq[55:0], data}; else h_count <= {h_count[7:0], data}; end")
    A("                    LENH: lenh <= data;")
    A("                    LENL: begin rem <= len_now; off <= 8'd0;")
    A("                        if (len_now == 16'd0) begin m_valid <= 1'b1; m_type <= 8'd0; m_err <= 2'd2; m_idx <= nblk; end end")
    A("                    BODY: begin")
    A("                        rem <= rem - 16'd1; if (off != 8'hff) off <= off + 8'd1;")
    A("                        if (off == 8'd0) begin ty <= data; er <= er_d; end")
    A("                        if (last_byte) begin m_valid <= 1'b1; m_type <= (off == 8'd0) ? data : ty; m_err <= (off == 8'd0) ? er_d : er; m_idx <= nblk; end")
    A("                    end")
    A("                    default: ;"); A("                endcase")
    A("            end")
    A("            if (eop && !sop && st != IDLE) begin p_valid <= 1'b1; p_trunc <= (st_n != LENH); p_cntbad <= (st_n == LENH) && (nblk_n != count_now) && (count_now != 16'hffff); st <= IDLE; end")
    A("            if (eop && sop) begin p_valid <= 1'b1; p_trunc <= 1'b1; p_cntbad <= 1'b0; st <= IDLE; end")
    A("        end")
    A("    end")
    A("    always_ff @(posedge clk) if (valid && !sop && !rst) begin")
    for nm, n in F.items(): A(f"        if (s_{nm}) f_{nm} <= {{f_{nm}[{8 * n - 9}:0], data}};" if n > 1 else f"        if (s_{nm}) f_{nm} <= data;")
    A("    end")
    A("endmodule")
    # a wrapper with a handful of pins, ONLY so that the design fits a chip for the place-and-route runs: the inputs are shifted in serially, all outputs are folded into one registered 16-bit word
    ow = 1 + 8 + 2 + 16 + 64 + 1 + 1 + 1 + 80 + 16 + sum(8 * n for n in F.values())
    A(f"module {name}_syn (input logic clk, input logic rst, input logic si, input logic sh, output logic [15:0] info);")
    A("    logic [10:0] iv; logic m_valid, p_valid, p_trunc, p_cntbad; logic [7:0] m_type; logic [1:0] m_err; logic [15:0] m_idx, h_count; logic [63:0] h_seq; logic [79:0] h_session;")
    for nm, n in F.items(): A(f"    logic [{8 * n - 1}:0] f_{nm};")
    A("    always_ff @(posedge clk) if (sh) iv <= {iv[9:0], si};")
    A(f"    {name} u (.clk(clk), .rst(rst), .valid(iv[10]), .sop(iv[9]), .eop(iv[8]), .data(iv[7:0]), .m_valid(m_valid), .m_type(m_type), .m_err(m_err), .m_idx(m_idx), .h_seq(h_seq), .p_valid(p_valid), .p_trunc(p_trunc), .p_cntbad(p_cntbad), .h_session(h_session), .h_count(h_count)" + "".join(f", .f_{nm}(f_{nm})" for nm in F) + ");")
    A(f"    logic [{ow - 1}:0] all; logic [15:0] x;")
    nch = (ow + 15) // 16; ng = (nch + 7) // 8
    A("    always_comb all = {m_valid, m_type, m_err, m_idx, h_seq, p_valid, p_trunc, p_cntbad, h_session, h_count" + "".join(f", f_{nm}" for nm in F) + "};")
    A(f"    logic [15:0] g1 [{ng}]; logic [{nch * 16 - 1}:0] allp; always_comb allp = {nch * 16}'(all);")
    A(f"    always_ff @(posedge clk) for (int q = 0; q < {ng}; q++) begin g1[q] <= 16'd0; for (int k = 0; k < 8; k++) if (q * 8 + k < {nch}) g1[q] <= g1[q] ^ 16'(allp >> ((q * 8 + k) * 16)); end")
    A("    always_comb begin x = 16'd0; for (int q = 0; q < " + str(ng) + "; q++) x ^= g1[q]; end")
    A("    always_ff @(posedge clk) info <= x;")
    A("endmodule")
    return "\n".join(L) + "\n"
def gen_tb_includes(g, outdir):
    """The three include files of tb/mold_tb.sv for a grammar: declarations, port connections and the print statement of a message."""
    F = grammar.fields(g)
    open(os.path.join(outdir, "mold_decl.vh"), "w").write("".join(f"    logic [{8 * n - 1}:0] f_{nm};\n" for nm, n in F.items()))
    open(os.path.join(outdir, "mold_conn.vh"), "w").write("".join(f"        , .f_{nm}(f_{nm})\n" for nm in F))
    open(os.path.join(outdir, "mold_print.vh"), "w").write('            $display("M %0d %0d %0d %0d %0d' + " %h" * len(F) + '", cyc, m_type, m_err, m_idx, h_seq' + "".join(f", f_{nm}" for nm in F) + ");\n")
    return list(F)
if __name__ == "__main__":
    name = sys.argv[1] if len(sys.argv) > 1 else "mold_itch"; out = sys.argv[2] if len(sys.argv) > 2 else "rtl/mold_itch.sv"; gname = sys.argv[3] if len(sys.argv) > 3 else "ITCH"
    open(out, "w").write(gen(getattr(grammar, gname), name)); print("wrote", out, "and", ", ".join(gen_tb_includes(getattr(grammar, gname), os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "out"))))
