#!/usr/bin/env python3
"""Chapter 17: the WIDE parser generator: grammar (model/grammar.py) -> a MoldUDP64 parser that takes W bytes per clock.
Usage: python3 tools/gen_parser_wide.py [W] [name] [out.sv] [version]     (defaults: 8 mold_wide8 rtl/mold_wide8.sv 1)
Interface (specified by model/wide_gold.py): in: clk rst valid sop eop nb[3:0] data[8W-1:0]; lane j is bits 8j+7:8j and lane 0 holds the EARLIEST byte; nb is the number of valid bytes (1..W; less than W only in the last beat of a packet); a beat with sop starts a packet at lane 0.
  out: m_valid m_type m_err m_idx h_seq f_<field>...   the first block that COMPLETES in a beat, registered, the cycle after the beat (err 0 ok, 1 unknown type, 2 wrong length or zero length); the f_ registers are a SNAPSHOT taken when the block completes, so the next message starting in the same beat cannot spoil them
       x_valid x_idx                                   a second block completing in the same beat: err 3, FRAMING ERROR: the packet is abandoned (the rest of it is ignored; its packet end reports trunc). Valid messages are at least 12 bytes + 2 of length, so for W <= 8 only erroneous blocks can do this
       p_valid p_trunc p_cntbad h_session h_count      as in Chapter 16
Version 1 is the straightforward design: the byte step of Chapter 16 unrolled W times in one combinational chain. Version 2 (see gen_pipe in this file) is the rebuilt one."""
import os, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "model"))
import grammar
HEAD = ["input logic clk, input logic rst, input logic valid, input logic sop, input logic eop, input logic [3:0] nb, input logic [{w8}:0] data,",
        "output logic m_valid, output logic [7:0] m_type, output logic [1:0] m_err, output logic [15:0] m_idx, output logic [63:0] h_seq,",
        "output logic x_valid, output logic [15:0] x_idx,",
        "output logic p_valid, output logic p_trunc, output logic p_cntbad, output logic [79:0] h_session, output logic [15:0] h_count,"]
def wrapper(F, name, W):
    """A wrapper with a handful of pins, ONLY so that the design fits a chip for the place-and-route runs: the inputs are shifted in serially, the outputs are folded (two register stages) into one 16-bit word."""
    iw = 8 * W + 7; ow = 1 + 8 + 2 + 16 + 64 + 1 + 16 + 3 + 80 + 16 + sum(8 * n for n in F.values()); nch = (ow + 15) // 16; ng = (nch + 7) // 8; L = []; A = L.append
    A(f"module {name}_syn (input logic clk, input logic rst, input logic si, input logic sh, output logic [15:0] info);")
    A(f"    logic [{iw - 1}:0] iv; logic m_valid, x_valid, p_valid, p_trunc, p_cntbad; logic [7:0] m_type; logic [1:0] m_err; logic [15:0] m_idx, x_idx, h_count; logic [63:0] h_seq; logic [79:0] h_session;")
    for nm, n in F.items(): A(f"    logic [{8 * n - 1}:0] f_{nm};")
    A(f"    always_ff @(posedge clk) if (sh) iv <= {{iv[{iw - 2}:0], si}};")
    A(f"    {name} u (.clk(clk), .rst(rst), .valid(iv[{iw - 1}]), .sop(iv[{iw - 2}]), .eop(iv[{iw - 3}]), .nb(iv[{8 * W + 3}:{8 * W}]), .data(iv[{8 * W - 1}:0]), .m_valid(m_valid), .m_type(m_type), .m_err(m_err), .m_idx(m_idx), .h_seq(h_seq), .x_valid(x_valid), .x_idx(x_idx), .p_valid(p_valid), .p_trunc(p_trunc), .p_cntbad(p_cntbad), .h_session(h_session), .h_count(h_count)" + "".join(f", .f_{nm}(f_{nm})" for nm in F) + ");")
    A(f"    logic [{ow - 1}:0] all; always_comb all = {{m_valid, m_type, m_err, m_idx, h_seq, x_valid, x_idx, p_valid, p_trunc, p_cntbad, h_session, h_count" + "".join(f", f_{nm}" for nm in F) + "};")
    A(f"    logic [15:0] g1 [{ng}]; logic [{nch * 16 - 1}:0] allp; always_comb allp = {nch * 16}'(all); logic [15:0] x;")
    A(f"    always_ff @(posedge clk) for (int q = 0; q < {ng}; q++) begin g1[q] <= 16'd0; for (int k = 0; k < 8; k++) if (q * 8 + k < {nch}) g1[q] <= g1[q] ^ 16'(allp >> ((q * 8 + k) * 16)); end")
    A(f"    always_comb begin x = 16'd0; for (int q = 0; q < {ng}; q++) x ^= g1[q]; end")
    A("    always_ff @(posedge clk) info <= x;"); A("endmodule")
    return "\n".join(L) + "\n"
def gen_pipe(g, name, W): return gen(g, name, W, 1)
def gen_v3(g, name, W): return gen(g, name, W, 2)
def gen(g, name, W, pipe=False):
    F = grammar.fields(g); L = []; A = L.append
    A(f"// GENERATED by tools/gen_parser_wide.py (version {1 + int(pipe)}) from model/grammar.py -- do not edit. W = {W} bytes per clock; {len(g)} message types, {len(F)} distinct fields.")
    A("// verilator lint_off DECLFILENAME"); A("// verilator lint_off UNUSEDSIGNAL"); A("// verilator lint_off BLKSEQ"); A("// verilator lint_off UNOPTFLAT")
    A(f"module {name} (\n    " + "\n    ".join(h.format(w8=8 * W - 1) for h in HEAD) + "\n    " + ",\n    ".join(f"output logic [{8 * n - 1}:0] f_{nm}" for nm, n in F.items()) + ");")
    A("    localparam logic [2:0] IDLE = 3'd0, HDR = 3'd1, LENH = 3'd2, LENL = 3'd3, BODY = 3'd4, DEAD = 3'd5;")
    A("    logic [2:0] st; logic [4:0] pos; logic [7:0] lenh, off, ty; logic [15:0] rem, nblk; logic [1:0] er;")
    A("    logic [79:0] ses; logic [63:0] seq; logic [15:0] cnt;")
    for nm, n in F.items(): A(f"    logic [{8 * n - 1}:0] w_{nm};")
    A("    // the chain: c_* are the state after the lanes processed so far")
    A("    logic [2:0] c_st; logic [4:0] c_pos; logic [7:0] c_lenh, c_off, c_ty, b, e_len, t_ty; logic [15:0] c_rem, c_nblk, c_cnt, c_len; logic [1:0] c_er, er_d, t_er; logic [79:0] c_ses; logic [63:0] c_seq; logic c_done, lastb;")
    A("    logic m_v, x_v, p_v, p_t, p_c; logic [7:0] m_t; logic [1:0] m_e; logic [15:0] m_i, x_i;")
    if pipe:
        A(f"    // version 2: stage 1 (this chain) only FRAMES: it tags every lane with its role; stage 2 assembles the fields from the registered tags")
        A(f"    logic [{W - 1}:0] tg_ok, tg_comp; logic [7:0] tg_off [{W}]; logic [7:0] tg_ty [{W}];")
    for nm, n in F.items(): A(f"    logic [{8 * n - 1}:0] n_{nm}, o_{nm};")
    A("    always_comb begin")
    A("        c_st = st; c_pos = pos; c_lenh = lenh; c_off = off; c_ty = ty; c_rem = rem; c_nblk = nblk; c_er = er; c_ses = ses; c_seq = seq; c_cnt = cnt; c_done = 1'b0;")
    A("        m_v = 1'b0; x_v = 1'b0; m_t = 8'd0; m_e = 2'd0; m_i = 16'd0; x_i = 16'd0; b = 8'd0; e_len = 8'd0; t_ty = 8'd0; t_er = 2'd0; er_d = 2'd0; lastb = 1'b0; c_len = 16'd0;")
    if not pipe:
        for nm in F: A(f"        n_{nm} = w_{nm}; o_{nm} = f_{nm};")
    jj = [0]
    complete = lambda ty, err, snap: ["            if (c_done) begin x_v = 1'b1; x_i = c_nblk; c_st = DEAD; end",
        "            else begin c_done = 1'b1; m_v = 1'b1; m_t = " + ty + "; m_e = " + err + "; m_i = c_nblk; c_nblk = c_nblk + 16'd1; c_st = LENH;" + (((" if (" + err + " == 2'd0) begin " if not pipe else " begin ") + ("tg_comp[" + str(jj[0]) + "] = 1'b1;" if pipe else " ".join(f"o_{nm} = n_{nm};" for nm in F)) + " end") if snap else "") + " end"]
    if pipe: A("        tg_ok = '0; tg_comp = '0; for (int q = 0; q < " + str(W) + "; q++) begin tg_off[q] = 8'd0; tg_ty[q] = 8'd0; end")
    for j in range(W):
        jj[0] = j
        A(f"        // ---- lane {j}"); A(f"        if ({j} < nb) begin")
        A(f"            b = data[{8 * j} +: 8];")
        A("            case (b)")
        for t, m in g.items(): A(f"                8'h{ord(t):02x}: e_len = 8'd{grammar.length(m)};")
        A("                default: e_len = 8'd0;"); A("            endcase")
        A("            er_d = (e_len == 8'd0) ? 2'd1 : (({8'd0, e_len} == c_rem) ? 2'd0 : 2'd2);")
        if j == 0:
            A("            if (sop) begin c_st = HDR; c_pos = 5'd1; c_nblk = 16'd0; " + ("c_ses[79:72] = b;" if pipe == 2 else "c_ses = {72'd0, b};") + " end else begin")
        else: A("            begin")
        A("            case (c_st)")
        if pipe == 2: A("                HDR: begin if (c_pos < 5'd10) c_ses[8 * (9 - c_pos) +: 8] = b; else if (c_pos < 5'd18) c_seq[8 * (17 - c_pos) +: 8] = b; else c_cnt[8 * (19 - c_pos) +: 8] = b; c_pos = c_pos + 5'd1; if (c_pos == 5'd20) c_st = LENH; end")
        else: A("                HDR: begin c_pos = c_pos + 5'd1; if (c_pos <= 5'd10) c_ses = {c_ses[71:0], b}; else if (c_pos <= 5'd18) c_seq = {c_seq[55:0], b}; else c_cnt = {c_cnt[7:0], b}; if (c_pos == 5'd20) c_st = LENH; end")
        A("                LENH: begin c_lenh = b; c_st = LENL; end")
        A("                LENL: begin c_len = {c_lenh, b}; c_rem = c_len; c_off = 8'd0;")
        A("                    if (c_len == 16'd0) begin"); L.extend(complete("8'd0", "2'd2", False)); A("                    end else c_st = BODY; end")
        A("                BODY: begin")
        A("                    lastb = (c_rem == 16'd1); t_ty = (c_off == 8'd0) ? b : c_ty; t_er = (c_off == 8'd0) ? er_d : c_er;")
        A("                    if (c_off == 8'd0) begin c_ty = b; c_er = er_d; end")
        if pipe: A(f"                    tg_ok[{j}] = (c_er == 2'd0); tg_off[{j}] = c_off; tg_ty[{j}] = c_ty;")
        else:
            for nm, n in F.items():
                terms = " || ".join(f"(c_ty == 8'h{ord(t):02x} && c_off >= 8'd{o} && c_off < 8'd{o + n_})" for t, o, n_ in [(t, 1 + sum(k for _, k in m[:[x for x, _ in m].index(nm)]), n) for t, m in g.items() if nm in [x for x, _ in m]])
                A(f"                    if (c_off != 8'd0 && c_er == 2'd0 && ({terms})) n_{nm} = " + (f"{{n_{nm}[{8 * n - 9}:0], b}};" if n > 1 else "b;"))
        A("                    c_rem = c_rem - 16'd1; if (c_off != 8'hff) c_off = c_off + 8'd1;")
        A("                    if (lastb) begin"); A("                        c_ty = t_ty; c_er = t_er;"); L.extend(["    " + x for x in complete("t_ty", "t_er", True)]); A("                    end end")
        A("                default: ;"); A("            endcase"); A("            end")
        A("        end")
    A("        p_v = eop && (c_st != IDLE); p_t = (c_st != LENH); p_c = (c_st == LENH) && (c_nblk != c_cnt) && (c_cnt != 16'hffff);")
    A("    end")
    def terms_of(nm, tyv, offv):
        n = F[nm]; out = []
        for t, m in g.items():
            names = [x for x, _ in m]
            if nm in names: o = 1 + sum(k for _, k in m[:names.index(nm)]); out.append(f"({tyv} == 8'h{ord(t):02x} && {offv} >= 8'd{o} && {offv} < 8'd{o + n})")
        return " || ".join(out)
    if not pipe:
        A("    always_ff @(posedge clk) begin")
        A("        m_valid <= 1'b0; x_valid <= 1'b0; p_valid <= 1'b0;")
        A("        if (rst) st <= IDLE;")
        A("        else if (valid) begin")
        A("            st <= eop ? IDLE : c_st; pos <= c_pos; lenh <= c_lenh; off <= c_off; ty <= c_ty; rem <= c_rem; nblk <= c_nblk; er <= c_er; ses <= c_ses; seq <= c_seq; cnt <= c_cnt;")
        A("            m_valid <= m_v; m_type <= m_t; m_err <= m_e; m_idx <= m_i; x_valid <= x_v; x_idx <= x_i; h_seq <= c_seq; h_session <= c_ses; h_count <= c_cnt;")
        A("            p_valid <= p_v; p_trunc <= p_t; p_cntbad <= p_c;")
        for nm in F: A(f"            w_{nm} <= n_{nm}; f_{nm} <= o_{nm};")
        A("        end"); A("    end"); A("endmodule")
    else:
        A(f"    logic v1; logic [{8 * W - 1}:0] d1; logic [{W - 1}:0] tg_ok1, tg_comp1; logic [7:0] tg_off1 [{W}]; logic [7:0] tg_ty1 [{W}]; logic m_v1, x_v1, p_v1, p_t1, p_c1; logic [7:0] m_t1; logic [1:0] m_e1; logic [15:0] m_i1, x_i1;")
        A("    always_ff @(posedge clk) begin")
        A("        v1 <= 1'b0;")
        A("        if (rst) st <= IDLE;")
        A("        else if (valid) begin")
        A("            st <= eop ? IDLE : c_st; pos <= c_pos; lenh <= c_lenh; off <= c_off; ty <= c_ty; rem <= c_rem; nblk <= c_nblk; er <= c_er; ses <= c_ses; seq <= c_seq; cnt <= c_cnt;")
        A("            v1 <= 1'b1; d1 <= data; tg_ok1 <= tg_ok; tg_comp1 <= tg_comp; m_v1 <= m_v; m_t1 <= m_t; m_e1 <= m_e; m_i1 <= m_i; x_v1 <= x_v; x_i1 <= x_i; p_v1 <= p_v; p_t1 <= p_t; p_c1 <= p_c;")
        A(f"            for (int q = 0; q < {W}; q++) begin tg_off1[q] <= tg_off[q]; tg_ty1[q] <= tg_ty[q]; end")
        A("        end"); A("    end")
        A("    logic [7:0] b2;")
        A("    // stage 2: the fields, from the registered tags")
        A("    always_comb begin")
        for nm in F: A(f"        n_{nm} = w_{nm}; o_{nm} = f_{nm};")
        A("        b2 = 8'd0;")
        for j in range(W):
            A(f"        b2 = d1[{8 * j} +: 8];")
            for nm, n in F.items(): A(f"        if (tg_ok1[{j}] && ({terms_of(nm, f'tg_ty1[{j}]', f'tg_off1[{j}]')})) n_{nm} = " + (f"{{n_{nm}[{8 * n - 9}:0], b2}};" if n > 1 else "b2;"))
            A(f"        if (tg_comp1[{j}]) begin " + " ".join(f"o_{nm} = n_{nm};" for nm in F) + " end")
        A("    end")
        A("    always_ff @(posedge clk) begin")
        A("        m_valid <= 1'b0; x_valid <= 1'b0; p_valid <= 1'b0;")
        A("        if (v1) begin")
        A("            m_valid <= m_v1; m_type <= m_t1; m_err <= m_e1; m_idx <= m_i1; x_valid <= x_v1; x_idx <= x_i1; h_seq <= seq; h_session <= ses; h_count <= cnt; p_valid <= p_v1; p_trunc <= p_t1; p_cntbad <= p_c1;")
        for nm in F: A(f"            w_{nm} <= n_{nm}; f_{nm} <= o_{nm};")
        A("        end"); A("    end"); A("endmodule")
    return "\n".join(L) + "\n" + wrapper(F, name, W)
def gen_tb_includes(g, outdir):
    F = grammar.fields(g)
    open(os.path.join(outdir, "wide_decl.vh"), "w").write("".join(f"    logic [{8 * n - 1}:0] f_{nm};\n" for nm, n in F.items()))
    open(os.path.join(outdir, "wide_conn.vh"), "w").write("".join(f"        , .f_{nm}(f_{nm})\n" for nm in F))
    open(os.path.join(outdir, "wide_print.vh"), "w").write('            $display("M %0d %0d %0d %0d %0d' + " %h" * len(F) + '", cyc, m_type, m_err, m_idx, h_seq' + "".join(f", f_{nm}" for nm in F) + ");\n")
if __name__ == "__main__":
    W = int(sys.argv[1]) if len(sys.argv) > 1 else 8; name = sys.argv[2] if len(sys.argv) > 2 else f"mold_wide{W}"; out = sys.argv[3] if len(sys.argv) > 3 else f"rtl/{name}.sv"
    open(out, "w").write((gen_pipe if (len(sys.argv) > 4 and sys.argv[4] == "2") else gen)(grammar.ITCH, name, W)); gen_tb_includes(grammar.ITCH, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "out")); print("wrote", out)
