#!/usr/bin/env python3
"""Chapter 10: generate the book's TOY standard-cell library: lib/toy.lib (for synthesis and area/delay) and lib/toy_cells.v (simulation models for gate-level simulation), from ONE table so they cannot disagree.
Areas are in NAND2 equivalents ('gate equivalents', GE), using typical textbook ratios; delays are one made-up number per cell in ns. It is NOT any real process: it is a scale for comparing designs and a way to exercise the flow. Usage: gen_toylib.py"""
import os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CELLS = [  # name, inputs, function (liberty syntax), verilog expression, area (NAND2 = 1.0), delay (ns, one value for every input)
 ("BUF",   ["A"], "A", "A", 1.00, 0.08), ("INV",   ["A"], "!A", "~A", 0.67, 0.04),
 ("NAND2", ["A","B"], "!(A&B)", "~(A & B)", 1.00, 0.07), ("NOR2",  ["A","B"], "!(A|B)", "~(A | B)", 1.00, 0.09),
 ("AND2",  ["A","B"], "(A&B)", "A & B", 1.33, 0.11), ("OR2",   ["A","B"], "(A|B)", "A | B", 1.33, 0.13),
 ("XOR2",  ["A","B"], "(A^B)", "A ^ B", 2.00, 0.16), ("XNOR2", ["A","B"], "!(A^B)", "~(A ^ B)", 2.00, 0.16),
 ("NAND3", ["A","B","C"], "!(A&B&C)", "~(A & B & C)", 1.50, 0.10), ("NOR3",  ["A","B","C"], "!(A|B|C)", "~(A | B | C)", 1.50, 0.13),
 ("AOI21", ["A","B","C"], "!((A&B)|C)", "~((A & B) | C)", 1.67, 0.11), ("OAI21", ["A","B","C"], "!((A|B)&C)", "~((A | B) & C)", 1.67, 0.11),
 ("MUX2",  ["A","B","S"], "((S&B)|(!S&A))", "S ? B : A", 2.33, 0.18),
]
DFF_AREA, DFF_CLK_TO_Q = 5.00, 0.30
lib = ['/* A TOY standard-cell library for the book (generated by tools/gen_toylib.py). Areas in NAND2 equivalents, delays in ns, both made up from textbook ratios. NOT any real process. */',
       'library(toy) {', '  delay_model : table_lookup;', '  time_unit : "1ns";', '  capacitive_load_unit(1, pf);', '  voltage_unit : "1V";', '  current_unit : "1mA";', '  pulling_resistance_unit : "1kohm";',
       '  lu_table_template(scalar) { variable_1 : input_net_transition; index_1("0"); }']
for n, ins, fn, v, a, d in CELLS:
    lib += [f'  cell({n}) {{', f'    area : {a};']
    for p in ins: lib.append(f'    pin({p}) {{ direction : input; capacitance : 0.01; }}')
    lib += ['    pin(Y) {', '      direction : output;', f'      function : "{fn}";']
    for p in ins: lib.append(f'      timing() {{ related_pin : "{p}"; timing_sense : non_unate; cell_rise(scalar) {{ values("{d}"); }} cell_fall(scalar) {{ values("{d}"); }} rise_transition(scalar) {{ values("0.01"); }} fall_transition(scalar) {{ values("0.01"); }} }}')
    lib += ['    }', '  }']
lib += ['  cell(DFF) {', f'    area : {DFF_AREA};', '    ff(IQ, IQN) { clocked_on : "CK"; next_state : "D"; }', '    pin(D) { direction : input; capacitance : 0.01; }', '    pin(CK) { direction : input; clock : true; capacitance : 0.01; }',
        f'    pin(Q) {{ direction : output; function : "IQ"; timing() {{ related_pin : "CK"; timing_type : rising_edge; cell_rise(scalar) {{ values("{DFF_CLK_TO_Q}"); }} cell_fall(scalar) {{ values("{DFF_CLK_TO_Q}"); }} rise_transition(scalar) {{ values("0.01"); }} fall_transition(scalar) {{ values("0.01"); }} }} }}', '  }', '}']
os.makedirs(os.path.join(ROOT, "lib"), exist_ok=True)
open(os.path.join(ROOT, "lib", "toy.lib"), "w").write("\n".join(lib) + "\n")
v = ["// Simulation models of the toy library (generated together with lib/toy.lib by tools/gen_toylib.py)."]
for n, ins, fn, ex, a, d in CELLS: v.append(f"module {n}({', '.join('input ' + p for p in ins)}, output Y); assign Y = {ex}; endmodule")
v.append("module DFF(input D, input CK, output reg Q);\n`ifdef POWERUP_ZERO\n    initial Q = 1'b0;      // a defined power-up state (real flip-flops power up to 0 or 1, unpredictably)\n`endif\n    always @(posedge CK) Q <= D;\nendmodule")
open(os.path.join(ROOT, "lib", "toy_cells.v"), "w").write("\n".join(v) + "\n"); print(f"lib/toy.lib and lib/toy_cells.v written: {len(CELLS)} combinational cells and one flip-flop")
