#!/usr/bin/env python3
"""Chapter 6: generate rtl/exp_lut.v, the lookup table for exp(-d/16) scaled to 16 bits: entry d (0..255) is round(65535 * exp(-d/16)).
It is computed with the `decimal` module at 50 digits, NOT with the floating-point math.exp that the golden model uses, so the table in the circuit and the table in the answer key are produced by two different computations and must agree. Usage: gen_exp_lut.py"""
import os
from decimal import Decimal, getcontext
getcontext().prec = 50
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
def entry(d): return int((Decimal(65535) * (-Decimal(d) / 16).exp()).to_integral_value(rounding="ROUND_HALF_EVEN"))
rows = ["        8'd%d: e = 16'd%d;" % (d, entry(d)) for d in range(256)]
src = ("// Chapter 6: exp(-d/16) in 16-bit fixed point: e = round(65535 * exp(-d/16)) for d = 0..255. GENERATED by tools/gen_exp_lut.py; do not edit by hand.\n"
       "// d is the distance below the maximum in units of 1/16, so the table covers 0 .. 15.94 below the max; from d = 189 (11.8 below the maximum) the entries are 0 (the 16-bit table cannot represent them).\n"
       "module exp_lut(input [7:0] d, output reg [15:0] e);\n    always @* begin\n        case (d)\n" + "\n".join(rows) + "\n        default: e = 16'd0;\n        endcase\n    end\nendmodule\n")
open(os.path.join(ROOT, "rtl", "exp_lut.v"), "w").write(src); print("rtl/exp_lut.v written;", sum(1 for d in range(256) if entry(d) == 0), "of 256 entries are zero; first nonzero-run ends at d =", max(d for d in range(256) if entry(d) > 0))
