/* Chapter 50 host test: the Bitcoin validator (050_btc.c) under AddressSanitizer + UBSan. Part 1: hashing and the compact target. Part 2: the real blocks (ten from testnet, the mainnet genesis) against their PUBLISHED hashes, heights and
 * linkage. Part 3: Bitcoin Core's own transaction vectors. Part 4: every rule, with blocks built here and mined at an easy target. Part 5: damage. PASS/FAIL per line; exit status 1 on any FAIL. Run from native/. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../050_btc.h"
static int pass_n, fail_n;
static void check(const char *name, int ok) { printf("%s %s\n", ok ? "PASS" : "FAIL", name); if (ok) { pass_n++; } else { fail_n++; } }
static btc_block_t B; static btc_tx_t T; static uint8_t blk[1 << 17];
static const char *DIR = "../data/btc/";
static uint32_t slurp(const char *name, uint8_t *dst, uint32_t cap) { char p[256]; snprintf(p, sizeof p, "%s%s", DIR, name); FILE *f = fopen(p, "rb"); if (!f) { printf("   cannot open %s\n", p); return 0; } uint32_t n = (uint32_t)fread(dst, 1, cap, f); fclose(f); return n; }
static void hex(const uint8_t *d, int reverse, char *out) { static const char H[] = "0123456789abcdef"; for (int i = 0; i < 32; i++) { uint8_t x = reverse ? d[31 - i] : d[i]; out[2 * i] = H[x >> 4]; out[2 * i + 1] = H[x & 15]; } out[64] = 0; }
/* ---- a tiny builder for transactions and blocks ---- */
static uint32_t put_varint(uint8_t *p, uint64_t v) { if (v < 0xfd) { p[0] = (uint8_t)v; return 1; } if (v <= 0xffff) { p[0] = 0xfd; p[1] = (uint8_t)v; p[2] = (uint8_t)(v >> 8); return 3; } p[0] = 0xfe; p[1] = (uint8_t)v; p[2] = (uint8_t)(v >> 8); p[3] = (uint8_t)(v >> 16); p[4] = (uint8_t)(v >> 24); return 5; }
static uint32_t put32(uint8_t *p, uint32_t v) { p[0] = (uint8_t)v; p[1] = (uint8_t)(v >> 8); p[2] = (uint8_t)(v >> 16); p[3] = (uint8_t)(v >> 24); return 4; }
static uint32_t put64(uint8_t *p, int64_t v) { uint64_t u = (uint64_t)v; put32(p, (uint32_t)u); put32(p + 4, (uint32_t)(u >> 32)); return 8; }
typedef struct { uint8_t prev[32]; uint32_t idx; uint8_t script[120]; uint32_t script_len; } in_t;
typedef struct { int64_t value; uint8_t script[48]; uint32_t script_len; } out_t;
static uint32_t mk_tx(uint8_t *p, const in_t *in, int n_in, const out_t *out, int n_out, const uint8_t *wit0, uint32_t wit0_len) { /* wit0: one 32-byte witness item for input 0, others empty */
    uint32_t o = 0; o += put32(p + o, 2); if (wit0) { p[o++] = 0; p[o++] = 1; }
    o += put_varint(p + o, (uint64_t)n_in);
    for (int i = 0; i < n_in; i++) { memcpy(p + o, in[i].prev, 32); o += 32; o += put32(p + o, in[i].idx); o += put_varint(p + o, in[i].script_len); memcpy(p + o, in[i].script, in[i].script_len); o += in[i].script_len; o += put32(p + o, 0xffffffffu); }
    o += put_varint(p + o, (uint64_t)n_out);
    for (int i = 0; i < n_out; i++) { o += put64(p + o, out[i].value); o += put_varint(p + o, out[i].script_len); memcpy(p + o, out[i].script, out[i].script_len); o += out[i].script_len; }
    if (wit0) { for (int i = 0; i < n_in; i++) { if (i == 0) { p[o++] = 1; p[o++] = (uint8_t)wit0_len; memcpy(p + o, wit0, wit0_len); o += wit0_len; } else { p[o++] = 0; } } }
    o += put32(p + o, 0); return o;
}
static uint8_t TX[8][600]; static uint32_t TXL[8];
static void coinbase(int k, int script_len, int64_t value) { in_t in; memset(&in, 0, sizeof in); in.idx = 0xffffffffu; in.script_len = (uint32_t)script_len; for (int i = 0; i < script_len; i++) { in.script[i] = (uint8_t)(i + 3); } out_t o; memset(&o, 0, sizeof o); o.value = value; o.script_len = 1; o.script[0] = 0x51; TXL[k] = mk_tx(TX[k], &in, 1, &o, 1, 0, 0); }
static void plain(int k, uint8_t seed, int n_in, int n_out, int64_t v0) { in_t in[3]; out_t o[3]; memset(in, 0, sizeof in); memset(o, 0, sizeof o); for (int i = 0; i < n_in; i++) { memset(in[i].prev, seed + i, 32); in[i].idx = (uint32_t)i; in[i].script_len = 2; in[i].script[0] = 0x51; in[i].script[1] = 0x52; } for (int i = 0; i < n_out; i++) { o[i].value = v0; o[i].script_len = 1; o[i].script[0] = 0x51; } TXL[k] = mk_tx(TX[k], in, n_in, o, n_out, 0, 0); }
static uint32_t assemble(const int *order, int n, uint32_t bits, int mine, uint8_t *out, const uint8_t *force_root) { /* a block from TX[order[i]]; mined at the easy limit unless mine == 0 */
    uint8_t ids[8][32]; btc_tx_t t; uint32_t nx; for (int i = 0; i < n; i++) { btc_tx_parse(TX[order[i]], TXL[order[i]], 0, &t, &nx); memcpy(ids[i], t.txid, 32); }
    uint8_t root[32], mut; btc_merkle((const uint8_t (*)[32])ids, (uint32_t)n, root, &mut); if (force_root) { memcpy(root, force_root, 32); }
    uint32_t o = 0; put32(out, 0x20000000); memset(out + 4, 0x11, 32); memcpy(out + 36, root, 32); put32(out + 68, 1700000000); put32(out + 72, bits); o = 80;
    for (uint32_t nonce = 0;; nonce++) { put32(out + 76, nonce); uint8_t h[32]; btc_dsha(out, 80, h); if (!mine || h[31] < 0x80) { break; } } /* 0x207fffff: target begins 7fffff..., so hash[31] < 0x80 passes (about half of all nonces) */
    o += put_varint(out + o, (uint64_t)n); for (int i = 0; i < n; i++) { memcpy(out + o, TX[order[i]], TXL[order[i]]); o += TXL[order[i]]; } return o;
}
static const char *verdict(const uint8_t *b, uint32_t len, uint32_t limit) { int rc = btc_block_parse(&B, b, len, limit); if (rc) { return btc_strerror(rc); } return B.reason ? B.reason : "VALID"; }
int main(void) {
    char h1[65]; uint8_t d[32];
    printf("== 1. hashing and the compact target ==\n");
    btc_dsha((const uint8_t *)"", 0, d); hex(d, 0, h1); check("double SHA-256 of the empty string is 5df6e0e2...", !strcmp(h1, "5df6e0e2761359d30a8275058e299fcc0381534545f55cf43e41983f5d4c9456"));
    btc_dsha((const uint8_t *)"abc", 3, d); hex(d, 0, h1); check("double SHA-256 of 'abc' is 4f8b42c2...", !strcmp(h1, "4f8b42c22dd3729b519ba6f68d2da7cc5b2d606d05daed5ad5128cc03e6c6358"));
    struct { uint32_t bits; int ok; const char *target_or_why; } cp[] = {
        {0x1d00ffff, 1, "00000000ffff0000000000000000000000000000000000000000000000000000"}, {0x1b0404cb, 1, "00000000000404cb000000000000000000000000000000000000000000000000"}, {0x03123456, 1, "0000000000000000000000000000000000000000000000000000000000123456"},
        {0x02123456, 1, "0000000000000000000000000000000000000000000000000000000000001234"}, {0x01123456, 1, "0000000000000000000000000000000000000000000000000000000000000012"},         {0x1d80ffff, 0, "negative"}, {0x04923456, 0, "negative"}, {0x01803456, 0, "negative"}, {0xff123456, 0, "overflow"}, {0x23000001, 0, "overflow"}, {0x1d000000, 0, "zero"}, {0x00000000, 0, "zero"}, {0x1e00ffff, 0, "above the limit"}, {0x22000100, 0, "overflow"}, {0x21010000, 0, "overflow"}, {0x207fffff, 0, "above the limit"}};
    int all = 1; for (size_t i = 0; i < sizeof cp / sizeof cp[0]; i++) { uint8_t t[32]; const char *why = ""; int ok = btc_compact(cp[i].bits, 0x1d00ffffu, t, &why); if (ok != cp[i].ok) { all = 0; printf("   bits %08x: ok=%d\n", cp[i].bits, ok); continue; } if (ok) { hex(t, 0, h1); if (strcmp(h1, cp[i].target_or_why)) { all = 0; printf("   bits %08x: %s\n", cp[i].bits, h1); } } else if (strcmp(why, cp[i].target_or_why)) { all = 0; printf("   bits %08x: why %s\n", cp[i].bits, why); } }
    check("16 compact-target cases against the 1d00ffff limit: the genesis target, 1b0404cb, tiny exponents; negative, overflow, zero and above-the-limit (1e00ffff and 207fffff) refused with their reason", all);
    { uint8_t t[32]; const char *why = ""; int ok = btc_compact(0x207fffffu, 0x207fffffu, t, &why); hex(t, 0, h1); check("the same 207fffff is accepted when it IS the limit, and expands to 7fffff followed by 29 zero bytes", ok && !strcmp(h1, "7fffff0000000000000000000000000000000000000000000000000000000000")); }
    printf("\n== 2. real blocks against their published hashes, heights and linkage ==\n");
    FILE *mf = fopen("../data/btc/MANIFEST.txt", "r"); char line[256], mh[16][65]; int mn = 0; char names[16][40]; (void)names;
    int hashes_ok = 1, valid_ok = 1, heights_ok = 1; int checked = 0;
    if (mf) { while (fgets(line, sizeof line, mf)) { char net[24], hs[80], fn[40]; int hgt; if (sscanf(line, "%23s %d %79s %39s", net, &hgt, hs, fn) == 4 && (!strcmp(net, "testnet") || !strcmp(net, "mainnet"))) {
        uint32_t n = slurp(fn, blk, sizeof blk); int rc = btc_block_parse(&B, blk, n, 0x1d00ffffu); hex(B.hash, 1, h1); checked++;
        if (rc != 0 || strcmp(h1, hs)) { hashes_ok = 0; printf("   %s: hash %s vs published %s\n", fn, h1, hs); }
        if (rc != 0 || B.reason) { valid_ok = 0; printf("   %s: %s\n", fn, B.reason ? B.reason : "parse error"); }
        if (B.version >= 2 && strcmp(net, "mainnet") && (!B.height_ok || B.height != hgt)) { heights_ok = 0; printf("   %s: BIP34 height %lld vs %d\n", fn, (long long)B.height, hgt); }
        mn++; (void)mh; } } fclose(mf); }
    check("all 11 real blocks (10 testnet3 + the mainnet genesis): the double-SHA-256 of each header equals the hash PUBLISHED in Bitcoin Core's test data", checked == 11 && hashes_ok);
    check("all 11 pass every context-free check (proof of work, Merkle root, coinbase, every transaction)", valid_ok);
    check("every real block of version 2 or later: the height in its coinbase (BIP 34) equals its published height (49291, 180480, 926485, 987876, 1263442, 1414221)", heights_ok);
    { uint32_t n = slurp("tn_926485.blk", blk, sizeof blk); btc_block_parse(&B, blk, n, 0x1d00ffffu); int a = B.witness == 1 && B.n_tx == 5 && B.tx[0].has_witness; n = slurp("tn_1263442.blk", blk, sizeof blk); btc_block_parse(&B, blk, n, 0x1d00ffffu); int b = B.witness == 1; n = slurp("tn_49291.blk", blk, sizeof blk); btc_block_parse(&B, blk, n, 0x1d00ffffu); int c = B.witness == 0 && B.n_tx == 2;
      check("the two real SegWit blocks (926485, 1263442): the coinbase's witness commitment equals double-SHA-256(witness Merkle root || witness reserved value); a pre-SegWit block has none", a && b && c); }
    { uint32_t n = slurp("mn_0.blk", blk, sizeof blk); btc_block_parse(&B, blk, n, 0x1d00ffffu); hex(B.computed_merkle, 1, h1); check("mainnet genesis: Merkle root 4a5e1e4baab89f3a... (= the txid of its single coinbase), 43 leading zero bits of proof of work, 285 bytes", !strcmp(h1, "4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b") && B.zero_bits == 43 && B.size == 285 && B.weight == 1140); }
    { uint8_t a[32], bb[32]; uint32_t n = slurp("tn_2.blk", blk, sizeof blk); btc_block_parse(&B, blk, n, 0x1d00ffffu); memcpy(a, B.hash, 32); n = slurp("tn_3.blk", blk, sizeof blk); btc_block_parse(&B, blk, n, 0x1d00ffffu); memcpy(bb, B.prev, 32); int link = !memcmp(a, bb, 32);
      n = slurp("tn_0.blk", blk, sizeof blk); btc_block_parse(&B, blk, n, 0x1d00ffffu); memcpy(a, B.hash, 32); n = slurp("tn_2.blk", blk, sizeof blk); btc_block_parse(&B, blk, n, 0x1d00ffffu); memcpy(bb, B.prev, 32); int gap = memcmp(a, bb, 32) != 0;
      check("linkage: testnet block 3's previous-hash field is block 2's hash; block 2's is NOT block 0's (block 1 lies between them)", link && gap); }
    { int chain_ok = 1; uint8_t prev[32]; for (int i = 1; i <= 12; i++) { char fn[24]; snprintf(fn, sizeof fn, "syn_%d.blk", i); uint32_t n = slurp(fn, blk, sizeof blk); int rc = btc_block_parse(&B, blk, n, 0x207fffffu); if (rc || B.reason || (i > 1 && memcmp(B.prev, prev, 32)) || !B.height_ok || B.height != i) { chain_ok = 0; printf("   syn_%d: %s\n", i, B.reason ? B.reason : "?"); } memcpy(prev, B.hash, 32); }
      check("the synthetic mined chain: 12 blocks, each valid, each linked to the one before, BIP 34 heights 1..12", chain_ok); }
    { uint32_t n = slurp("syn_6.blk", blk, sizeof blk); btc_block_parse(&B, blk, n, 0x207fffffu); int w = B.witness == 1; n = slurp("syn_dup.blk", blk, sizeof blk); int rc = btc_block_parse(&B, blk, n, 0x207fffffu); check("synthetic SegWit block: commitment PASS; the block with a duplicated transaction has the RIGHT Merkle root, is flagged mutated and refused as bad-txns-duplicate", w && rc == 0 && B.merkle_mutated && !memcmp(B.computed_merkle, B.merkle, 32) && B.reason && !strcmp(B.reason, "bad-txns-duplicate")); }
    { uint32_t n = slurp("tn_49291.blk", blk, sizeof blk); btc_block_parse(&B, blk, n, 0x1d00ffffu); check("a block valid under the mainnet/testnet limit is refused under a HARDER limit (0x1c00ffff): the target is above it", (btc_block_parse(&B, blk, n, 0x1c00ffffu) == 0 && B.reason && !strcmp(B.reason, "high-hash"))); }
    printf("\n== 3. Bitcoin Core's transaction test vectors (tx_valid.json, tx_invalid.json) ==\n");
    static uint8_t tv[1 << 18]; uint32_t tvn = slurp("txvec.bin", tv, sizeof tv); uint32_t i = 0; int nv = 0, ni = 0, v_ok = 1, i_cf_ok = 1, i_pass = 0, parsed_all = 1; int cat_seen[9] = {0};
    static const char *CAT[9] = {"", "bad-txns-vout-empty", "bad-txns-vout-negative", "bad-txns-vout-toolarge", "bad-txns-txouttotal-toolarge", "bad-txns-inputs-duplicate", "bad-cb-length", "bad-txns-prevout-null", ""};
    while (i + 4 <= tvn) { uint8_t kind = tv[i], exp = tv[i + 1]; uint32_t ln = (uint32_t)tv[i + 2] | (uint32_t)tv[i + 3] << 8; uint32_t nx; int rc = btc_tx_parse(tv + i + 4, ln, 0, &T, &nx); i += 4 + ln;
        if (rc != 0 || nx != ln) { parsed_all = 0; continue; }
        if (kind == 0) { nv++; if (T.check) { v_ok = 0; printf("   valid vector refused: %s\n", T.check); } }
        else { ni++; if (exp == 0) { if (T.check) { i_cf_ok = 0; printf("   a script-level invalid vector failed a context-free check: %s\n", T.check); } else { i_pass++; } } else { cat_seen[exp]++; if (!T.check || strcmp(T.check, CAT[exp])) { i_cf_ok = 0; printf("   category %u: wanted %s got %s\n", exp, CAT[exp], T.check ? T.check : "ok"); } } } }
    check("all 214 raw transactions of Core's vectors parse exactly (legacy and SegWit serialisation, every length field)", parsed_all && nv == 121 && ni == 93);
    check("all 121 transactions of tx_valid.json pass every context-free check", v_ok);
    check("the nine 'Tests for CheckTransaction()' entries of tx_invalid.json fail with exactly the reasons Core's labels give: no outputs, negative output, MAX_MONEY+1, total over MAX_MONEY, duplicate inputs, coinbase script of 1 and of 101 bytes, null input in a non-coinbase (x2)", i_cf_ok && cat_seen[1] == 1 && cat_seen[2] == 1 && cat_seen[3] == 1 && cat_seen[4] == 1 && cat_seen[5] == 1 && cat_seen[6] == 2 && cat_seen[7] == 2);
    check("the other 84 invalid vectors are invalid only at the SCRIPT level (signatures, locktimes, witness programs) and so correctly pass the context-free checks", i_pass == 84);
    printf("\n== 4. every rule, with blocks built and mined here at the easy limit 0x207fffff ==\n");
    const uint32_t EASY = 0x207fffffu; int ord[8]; uint32_t n;
    coinbase(0, 8, 2500000000ll); plain(1, 0x40, 1, 2, 1000); plain(2, 0x50, 2, 1, 2000);
    ord[0] = 0; ord[1] = 1; ord[2] = 2; n = assemble(ord, 3, EASY, 1, blk, 0); check("a valid three-transaction block", !strcmp(verdict(blk, n, EASY), "VALID") && B.n_tx == 3 && B.pow_ok);
    ord[0] = 1; ord[1] = 2; n = assemble(ord, 2, EASY, 1, blk, 0); check("no coinbase: bad-cb-missing", !strcmp(verdict(blk, n, EASY), "bad-cb-missing"));
    coinbase(3, 8, 100); ord[0] = 0; ord[1] = 3; ord[2] = 1; n = assemble(ord, 3, EASY, 1, blk, 0); check("a second coinbase: bad-cb-multiple", !strcmp(verdict(blk, n, EASY), "bad-cb-multiple"));
    coinbase(4, 1, 100); ord[0] = 4; ord[1] = 1; n = assemble(ord, 2, EASY, 1, blk, 0); check("coinbase script of 1 byte: bad-cb-length", !strcmp(verdict(blk, n, EASY), "bad-cb-length"));
    coinbase(4, 100, 100); ord[0] = 4; n = assemble(ord, 1, EASY, 1, blk, 0); check("coinbase script of exactly 100 bytes: accepted; 101: bad-cb-length", !strcmp(verdict(blk, n, EASY), "VALID")); coinbase(4, 101, 100); n = assemble(ord, 1, EASY, 1, blk, 0); check("... 101 bytes", !strcmp(verdict(blk, n, EASY), "bad-cb-length"));
    coinbase(4, 2, 100); ord[0] = 4; n = assemble(ord, 1, EASY, 1, blk, 0); check("coinbase script of exactly 2 bytes: accepted", !strcmp(verdict(blk, n, EASY), "VALID"));
    plain(5, 0x60, 1, 1, -1); ord[0] = 0; ord[1] = 5; n = assemble(ord, 2, EASY, 1, blk, 0); check("a negative output value (-1): bad-txns-vout-negative", !strcmp(verdict(blk, n, EASY), "bad-txns-vout-negative"));
    plain(5, 0x60, 1, 1, BTC_MAX_MONEY); n = assemble(ord, 2, EASY, 1, blk, 0); check("an output of exactly 21,000,000 coins: accepted", !strcmp(verdict(blk, n, EASY), "VALID"));
    plain(5, 0x60, 1, 1, BTC_MAX_MONEY + 1); n = assemble(ord, 2, EASY, 1, blk, 0); check("... one satoshi more: bad-txns-vout-toolarge", !strcmp(verdict(blk, n, EASY), "bad-txns-vout-toolarge"));
    plain(5, 0x60, 1, 2, BTC_MAX_MONEY / 2 + 1); n = assemble(ord, 2, EASY, 1, blk, 0); check("two outputs each valid but summing above the cap: bad-txns-txouttotal-toolarge", !strcmp(verdict(blk, n, EASY), "bad-txns-txouttotal-toolarge"));
    plain(5, 0x60, 2, 1, 1000); memcpy(TX[5] + 5 + 36 + 1 + 2 + 4, TX[5] + 5, 0); /* make input 1 equal input 0: same prev hash, same index */ { uint32_t o2 = 5 + 36 + 1 + 2 + 4; memcpy(TX[5] + o2, TX[5] + 5, 32); put32(TX[5] + o2 + 32, 0); } n = assemble(ord, 2, EASY, 1, blk, 0); check("the same input twice: bad-txns-inputs-duplicate", !strcmp(verdict(blk, n, EASY), "bad-txns-inputs-duplicate"));
    { in_t in; memset(&in, 0, sizeof in); in.idx = 0xffffffffu; in.script_len = 2; out_t o; memset(&o, 0, sizeof o); o.value = 5; o.script_len = 1; o.script[0] = 0x51; TXL[5] = mk_tx(TX[5], &in, 1, &o, 1, 0, 0); } ord[1] = 5; n = assemble(ord, 2, EASY, 1, blk, 0); check("a second coinbase-shaped transaction: bad-cb-multiple", !strcmp(verdict(blk, n, EASY), "bad-cb-multiple"));
    { in_t in[2]; memset(in, 0, sizeof in); in[0].idx = 0xffffffffu; in[0].script_len = 2; memset(in[1].prev, 7, 32); in[1].script_len = 2; out_t o; memset(&o, 0, sizeof o); o.value = 5; o.script_len = 1; o.script[0] = 0x51; TXL[5] = mk_tx(TX[5], in, 2, &o, 1, 0, 0); } n = assemble(ord, 2, EASY, 1, blk, 0); check("a null input in a transaction that is not a coinbase (it has two inputs): bad-txns-prevout-null", !strcmp(verdict(blk, n, EASY), "bad-txns-prevout-null"));
    { out_t o; memset(&o, 0, sizeof o); in_t in; memset(&in, 0, sizeof in); in.script_len = 2; TXL[5] = mk_tx(TX[5], &in, 1, &o, 0, 0, 0); } n = assemble(ord, 2, EASY, 1, blk, 0); check("a transaction with no outputs: bad-txns-vout-empty", !strcmp(verdict(blk, n, EASY), "bad-txns-vout-empty"));
    { uint8_t tx[16]; uint32_t o2 = 0; o2 += put32(tx, 2); tx[o2++] = 0; tx[o2++] = 0; /* zero inputs and zero outputs: but 00 00 reads as marker 00 + flag 00 = not a witness */ o2 += put32(tx + o2, 0); uint32_t nx; btc_tx_t t2; int rc = btc_tx_parse(tx, o2, 0, &t2, &nx); check("version | 00 00 | locktime: zero inputs, zero outputs, no witness flag: parses, then bad-txns-vin-empty", rc == 0 && t2.check && !strcmp(t2.check, "bad-txns-vin-empty")); }
    ord[0] = 0; ord[1] = 1; ord[2] = 2; n = assemble(ord, 3, EASY, 1, blk, 0); { uint8_t wrong[32]; memset(wrong, 0x5a, 32); n = assemble(ord, 3, EASY, 1, blk, wrong); check("a wrong Merkle root: bad-txnmrklroot", !strcmp(verdict(blk, n, EASY), "bad-txnmrklroot")); }
    n = assemble(ord, 3, EASY, 0, blk, 0); put32(blk + 76, 0); { int tries = 0; for (uint32_t nn = 0; nn < 64; nn++) { put32(blk + 76, nn); uint8_t h[32]; btc_dsha(blk, 80, h); if (h[31] >= 0x80) { tries = 1; break; } } check("a nonce whose hash is above the target: high-hash", tries && !strcmp(verdict(blk, n, EASY), "high-hash")); }
    n = assemble(ord, 3, 0x1d80ffffu, 0, blk, 0); check("negative compact target: high-hash, and the target is reported invalid (negative)", !strcmp(verdict(blk, n, EASY), "high-hash") && !B.target_ok && !strcmp(B.target_why, "negative"));
    n = assemble(ord, 3, 0xff00ffffu, 0, blk, 0); check("overflowing compact target: high-hash, target invalid (overflow)", !strcmp(verdict(blk, n, EASY), "high-hash") && !strcmp(B.target_why, "overflow"));
    n = assemble(ord, 3, 0x1d000000u, 0, blk, 0); check("zero compact target: high-hash, target invalid (zero)", !strcmp(verdict(blk, n, EASY), "high-hash") && !strcmp(B.target_why, "zero"));
    { /* merkle shapes: duplicated transaction */ ord[0] = 0; ord[1] = 1; ord[2] = 2; ord[3] = 2; n = assemble(ord, 4, EASY, 1, blk, 0); const char *v = verdict(blk, n, EASY); int ok = !strcmp(v, "bad-txns-duplicate") && B.merkle_mutated; uint8_t r4[32]; memcpy(r4, B.computed_merkle, 32); ord[3] = 0; n = assemble(ord, 3, EASY, 1, blk, 0); verdict(blk, n, EASY);
      check("[cb, a, b, b] and [cb, a, b] have the SAME Merkle root; the first is flagged mutated and refused, the second is valid (CVE-2012-2459)", ok && !memcmp(r4, B.computed_merkle, 32) && !B.merkle_mutated && !B.reason); }
    { uint8_t l[8][32], r1[32], r2[32], m; for (int k = 0; k < 8; k++) { memset(l[k], k + 1, 32); } btc_merkle((const uint8_t (*)[32])l, 1, r1, &m); int a = !memcmp(r1, l[0], 32) && !m; btc_merkle((const uint8_t (*)[32])l, 2, r1, &m); uint8_t pair[64]; memcpy(pair, l[0], 32); memcpy(pair + 32, l[1], 32); btc_dsha(pair, 64, r2); int b = !memcmp(r1, r2, 32);
      btc_merkle((const uint8_t (*)[32])l, 3, r1, &m); uint8_t x[32], y[32]; memcpy(pair + 32, l[1], 32); btc_dsha(pair, 64, x); memcpy(pair, l[2], 32); memcpy(pair + 32, l[2], 32); btc_dsha(pair, 64, y); memcpy(pair, x, 32); memcpy(pair + 32, y, 32); btc_dsha(pair, 64, r2); int c = !memcmp(r1, r2, 32) && !m;
      btc_merkle((const uint8_t (*)[32])l, 0, r1, &m); int e = 1; for (int k = 0; k < 32; k++) { if (r1[k]) { e = 0; } }
      check("Merkle shapes: one leaf is its own root; two leaves hash as a pair; three leaves duplicate the third; no leaves give 32 zero bytes", a && b && c && e); }
    { /* witness commitment */ uint8_t cbw[400], res[32]; memset(res, 0, 32); in_t in; memset(&in, 0, sizeof in); in.idx = 0xffffffffu; in.script_len = 4; out_t o[2]; memset(o, 0, sizeof o); o[0].value = 5; o[0].script_len = 1; o[0].script[0] = 0x51; o[1].script_len = 38; memcpy(o[1].script, "\x6a\x24\xaa\x21\xa9\xed", 6);
      plain(1, 0x70, 1, 1, 10); uint32_t l1 = TXL[1]; (void)l1; btc_tx_t t1; uint32_t nx; btc_tx_parse(TX[1], TXL[1], 0, &t1, &nx); /* a non-witness other transaction: its wtxid equals its txid */
      uint8_t wl[2][32]; memset(wl[0], 0, 32); memcpy(wl[1], t1.wtxid, 32); uint8_t wroot[32], m, cat[64], commit[32]; btc_merkle((const uint8_t (*)[32])wl, 2, wroot, &m); memcpy(cat, wroot, 32); memcpy(cat + 32, res, 32); btc_dsha(cat, 64, commit); memcpy(o[1].script + 6, commit, 32);
      TXL[6] = mk_tx(TX[6], &in, 1, o, 2, res, 32); (void)cbw; ord[0] = 6; ord[1] = 1; n = assemble(ord, 2, EASY, 1, blk, 0); check("a SegWit block whose coinbase carries the right witness commitment (witness reserved value 32 zero bytes): valid, witness PASS", !strcmp(verdict(blk, n, EASY), "VALID") && B.witness == 1);
      memset(o[1].script + 6, 0x33, 32); TXL[6] = mk_tx(TX[6], &in, 1, o, 2, res, 32); n = assemble(ord, 2, EASY, 1, blk, 0); check("the same block with a wrong commitment: bad-witness-merkle-match", !strcmp(verdict(blk, n, EASY), "bad-witness-merkle-match") && B.witness == 2);
      memcpy(o[1].script + 6, commit, 32); uint8_t res2[32]; memset(res2, 9, 32); TXL[6] = mk_tx(TX[6], &in, 1, o, 2, res2, 32); n = assemble(ord, 2, EASY, 1, blk, 0); check("the right commitment but a different witness reserved value: bad-witness-merkle-match (the reserved value is part of the hash)", !strcmp(verdict(blk, n, EASY), "bad-witness-merkle-match")); }
    printf("\n== 4b. limits and corner cases of the serialisation ==\n");
    { uint8_t tx[64]; uint32_t o = 0; btc_tx_t t2; uint32_t nx; o += put32(tx, 2); tx[o++] = 0; tx[o++] = 2; tx[o++] = 1; memset(tx + o, 0, 32); o += 32; o += put32(tx + o, 0); tx[o++] = 0; o += put32(tx + o, 0xffffffffu); tx[o++] = 0; o += put32(tx + o, 0);
      check("a transaction whose marker/flag bytes are 00 02 (only flag 01 exists): refused as an unknown flag", btc_tx_parse(tx, o, 0, &t2, &nx) == BTC_ERR_FLAG); }
    { uint8_t tx[80]; uint32_t o = 0; btc_tx_t t2; uint32_t nx; o += put32(tx, 2); tx[o++] = 0; tx[o++] = 1; tx[o++] = 1; memset(tx + o, 3, 32); o += 32; o += put32(tx + o, 0); tx[o++] = 0; o += put32(tx + o, 0xffffffffu); tx[o++] = 1; o += put64(tx + o, 5); tx[o++] = 1; tx[o++] = 0x51; tx[o++] = 0; /* the witness for the one input: zero items */ o += put32(tx + o, 0);
      check("the witness flag set but every witness empty: refused as superfluous (Bitcoin Core refuses it too)", btc_tx_parse(tx, o, 0, &t2, &nx) == BTC_ERR_SUPERFLUOUS_WITNESS); }
    { uint8_t tx[40]; uint32_t o = 0; btc_tx_t t2; uint32_t nx; memset(tx, 0, sizeof tx); o += put32(tx, 2); tx[o++] = 0xfd; tx[o++] = 0x01; tx[o++] = 0x10; /* 0x1001 = 4097 inputs */ check("a transaction announcing 4097 inputs: refused before reading them (the table holds 4096)", btc_tx_parse(tx, 40, 0, &t2, &nx) == BTC_ERR_TOO_MANY_IN); }
    { uint8_t hdr[100]; memset(hdr, 0, sizeof hdr); uint32_t o = 80; hdr[o++] = 0xfd; hdr[o++] = 0x01; hdr[o++] = 0x02; /* 513 transactions */ memset(hdr + o, 0, 10); check("a block announcing 513 transactions: refused (the table holds 512)", btc_block_parse(&B, hdr, 90, EASY) == BTC_ERR_TOO_MANY_TX);
      hdr[80] = 0; check("a block announcing no transactions: refused", btc_block_parse(&B, hdr, 85, EASY) == BTC_ERR_NO_TX); }
    { coinbase(4, 4, 100); TX[4][5 + 36 + 1] = 0x01; TX[4][5 + 36 + 2] = 0x81; ord[0] = 4; n = assemble(ord, 1, EASY, 1, blk, 0); btc_block_parse(&B, blk, n, EASY); check("a coinbase script starting with the one-byte push 0x81 (the sign bit set): BIP 34 reads the height as -1", B.height_ok && B.height == -1); }
    { plain(5, 0x60, 1, 2, BTC_MAX_MONEY / 2); ord[0] = 0; ord[1] = 5; coinbase(0, 8, 2500000000ll); n = assemble(ord, 2, EASY, 1, blk, 0); check("two outputs that sum to EXACTLY 21,000,000 coins: accepted", !strcmp(verdict(blk, n, EASY), "VALID")); }
    { static uint8_t big[1100000]; static uint8_t bblk[1100200]; in_t *in = (in_t *)malloc(sizeof(in_t)); memset(in, 0, sizeof *in); memset(in->prev, 9, 32); in->script_len = 0; out_t o1; memset(&o1, 0, sizeof o1); o1.value = 1; o1.script_len = 1; o1.script[0] = 0x51;
      uint32_t o = 0; o += put32(big, 2); o += put_varint(big + o, 1); memcpy(big + o, in->prev, 32); o += 32; o += put32(big + o, 0); o += put_varint(big + o, 1000000 - 100); /* script of 999,900 bytes */ memset(big + o, 0x51, 999900); o += 999900; o += put32(big + o, 0xffffffffu); o += put_varint(big + o, 1); o += put64(big + o, 1); big[o++] = 1; big[o++] = 0x51; o += put32(big + o, 0);
      btc_tx_t t2; uint32_t nx; int rc = btc_tx_parse(big, o, 0, &t2, &nx); check("a transaction with a 999,900-byte script (weight about 3,999,800): accepted", rc == 0 && !t2.check);
      /* make it 200 bytes longer: weight over 4,000,000 */ uint32_t o2 = 0; o2 += put32(big, 2); o2 += put_varint(big + o2, 1); memcpy(big + o2, in->prev, 32); o2 += 32; o2 += put32(big + o2, 0); o2 += put_varint(big + o2, 1000100); /* 0xfe + 4 bytes */ memset(big + o2, 0x51, 1000100); o2 += 1000100; o2 += put32(big + o2, 0xffffffffu); o2 += put_varint(big + o2, 1); o2 += put64(big + o2, 1); big[o2++] = 1; big[o2++] = 0x51; o2 += put32(big + o2, 0);
      rc = btc_tx_parse(big, o2, 0, &t2, &nx); check("a transaction of 1,000,100 script bytes: weight over 4,000,000: bad-txns-oversize", rc == 0 && t2.check && !strcmp(t2.check, "bad-txns-oversize"));
      free(in); (void)bblk; }
    { uint8_t *h = malloc(82); memset(h, 0, 82); h[80] = 0xfd; h[81] = 1; int rc = btc_block_parse(&B, h, 82, EASY); free(h); check("a block whose transaction count is a 0xfd prefix with only ONE of its two bytes present (heap buffer of exactly 82 bytes): refused, never read past the end", rc == BTC_ERR_SHORT); }
    { static uint8_t big[1300000], t0[700000], t1[700000]; uint32_t o, l0, l1; btc_tx_t tt; uint32_t nx;
      for (int k = 0; k < 2; k++) { uint8_t *p = k ? t1 : t0; o = 0; o += put32(p, 2); o += put_varint(p + o, 1); memset(p + o, 0x30 + k, 32); o += 32; o += put32(p + o, 0); o += put_varint(p + o, 600000); memset(p + o, 0x51, 600000); o += 600000; o += put32(p + o, 0xffffffffu); o += put_varint(p + o, 1); o += put64(p + o, 1); p[o++] = 1; p[o++] = 0x51; o += put32(p + o, 0); if (k) { l1 = o; } else { l0 = o; } }
      /* the first is made a coinbase by giving it the null input */ memset(t0 + 5, 0, 32); put32(t0 + 5 + 32, 0xffffffffu); put_varint(t0 + 5 + 36, 600000); /* script length stays 600000: too long for a coinbase, which would fail first */ 
      uint8_t ids[2][32], root[32], mut; btc_tx_parse(t0, l0, 0, &tt, &nx); int cbl = tt.check != 0; memcpy(ids[0], tt.txid, 32); btc_tx_parse(t1, l1, 0, &tt, &nx); int ok1 = tt.check == 0 && tt.weight == 4 * l1; memcpy(ids[1], tt.txid, 32); btc_merkle((const uint8_t (*)[32])ids, 2, root, &mut);
      check("two 600 KB transactions: each is under the 4,000,000 weight limit on its own (the first is refused only for its coinbase script length)", cbl && ok1 && l1 > 600000); (void)big; (void)root; }
    { /* a block over the weight limit whose only complaint is its weight: a coinbase of a small script plus one 1,000,001-byte-script transaction pair */ static uint8_t big[2200000], a[1100000], b2[1100000]; uint32_t la, lb, o;
      for (int k = 0; k < 2; k++) { uint8_t *p = k ? b2 : a; o = 0; o += put32(p, 2); o += put_varint(p + o, 1); if (k == 0) { memset(p + o, 0, 32); o += 32; o += put32(p + o, 0xffffffffu); o += put_varint(p + o, 100); memset(p + o, 0x51, 100); o += 100; } else { memset(p + o, 0x77, 32); o += 32; o += put32(p + o, 0); o += put_varint(p + o, 999000); memset(p + o, 0x51, 999000); o += 999000; }
        o += put32(p + o, 0xffffffffu); o += put_varint(p + o, 1); o += put64(p + o, 1); p[o++] = 1; p[o++] = 0x51; o += put32(p + o, 0); if (k) { lb = o; } else { la = o; } }
      /* b2 repeated with different prevouts: three of them: weight 3 x 4 x ~1MB = 12M > 4M, each alone 4.0M? 999,0xx x 4 = 3.996M: under the limit */
      static uint8_t c[1100000]; memcpy(c, b2, lb); memset(c + 5 + 1, 0x78, 32); static uint8_t d3[1100000]; memcpy(d3, b2, lb); memset(d3 + 5 + 1, 0x79, 32);
      uint8_t *txs[3] = {b2, c, a}; uint32_t ls[3] = {lb, lb, la}; (void)d3; uint8_t ids[3][32], root[32], mut; btc_tx_t tt; uint32_t nx; int allok = 1;
      for (int i = 0; i < 3; i++) { btc_tx_parse(txs[i], ls[i], 0, &tt, &nx); memcpy(ids[i], tt.txid, 32); if (i < 2 && tt.check) { allok = 0; } }
      /* order: coinbase first */ uint8_t *ord2[3] = {a, b2, c}; uint32_t lo[3] = {la, lb, lb}; uint8_t ids2[3][32]; for (int i = 0; i < 3; i++) { btc_tx_parse(ord2[i], lo[i], 0, &tt, &nx); memcpy(ids2[i], tt.txid, 32); } btc_merkle((const uint8_t (*)[32])ids2, 3, root, &mut);
      uint32_t bo = 0; put32(big, 0x20000000); memset(big + 4, 0x11, 32); memcpy(big + 36, root, 32); put32(big + 68, 1700000000); put32(big + 72, EASY); for (uint32_t nonce = 0;; nonce++) { put32(big + 76, nonce); uint8_t hh[32]; btc_dsha(big, 80, hh); if (hh[31] < 0x80) { break; } }
      bo = 80; bo += put_varint(big + bo, 3); for (int i = 0; i < 3; i++) { memcpy(big + bo, ord2[i], lo[i]); bo += lo[i]; }
      static uint8_t bigblk[3300000]; memcpy(bigblk, big, bo); const char *v = verdict(bigblk, bo, EASY);
      check("a block of three transactions each under the weight limit but together over 4,000,000: refused as bad-blk-length (and only for that)", allok && !strcmp(v, "bad-blk-length") && B.weight > 4000000u); }
    printf("\n== 5. damage ==\n");
    { uint32_t nn = slurp("tn_926485.blk", blk, sizeof blk); int survived = 0; for (int k = 0; k < 80; k++) { blk[k] ^= 0x01; int rc = btc_block_parse(&B, blk, nn, 0x1d00ffffu); if (rc == 0 && !B.reason) { survived++; } blk[k] ^= 0x01; } check("flipping any single bit of any of the 80 header bytes of a real SegWit block: never valid (80 of 80 refused)", survived == 0);
      int ok = 1; for (uint32_t k = 80; k < nn; k++) { blk[k] ^= 0x01; int rc = btc_block_parse(&B, blk, nn, 0x1d00ffffu); if (rc == 0 && !B.reason) { ok = 0; printf("   byte %u survived\n", k); break; } blk[k] ^= 0x01; } check("a real SegWit block (926485): flipping one bit of ANY byte after the header, witness bytes included, is never valid (the witness commitment covers what the txids do not)", ok); }
    { uint32_t nn = slurp("tn_49291.blk", blk, sizeof blk); int ok = 1; for (uint32_t k = 80; k < nn; k++) { blk[k] ^= 0x01; int rc = btc_block_parse(&B, blk, nn, 0x1d00ffffu); if (rc == 0 && !B.reason) { ok = 0; printf("   byte %u survived\n", k); } blk[k] ^= 0x01; }
      check("a real pre-SegWit block (49291): flipping one bit of each of its transaction bytes in turn is NEVER valid (every byte is covered by the Merkle root, a length field or a rule)", ok);
      int trunc_ok = 1; for (uint32_t k = 0; k < nn; k++) { int rc = btc_block_parse(&B, blk, k, 0x1d00ffffu); if (rc == 0 && !B.reason) { trunc_ok = 0; } } check("truncating that block at every possible length: never valid", trunc_ok);
      static uint8_t ext[1 << 12]; memcpy(ext, blk, nn); ext[nn] = 0; check("one extra byte after the last transaction: refused as trailing bytes", btc_block_parse(&B, ext, nn + 1, 0x1d00ffffu) == BTC_ERR_TRAILING); }
    { uint32_t nn = slurp("tn_926485.blk", blk, sizeof blk); /* flip a bit inside the coinbase witness reserved value: not covered by the Merkle root of txids, covered by the commitment */ btc_block_parse(&B, blk, nn, 0x1d00ffffu); uint32_t off = B.tx[0].wit0_item0_off; blk[off] ^= 1; int rc = btc_block_parse(&B, blk, nn, 0x1d00ffffu); check("a bit flipped in the coinbase's witness reserved value of a real SegWit block: the Merkle root still matches (witness data is not in the txid) but the witness commitment FAILS", rc == 0 && B.pow_ok && !memcmp(B.computed_merkle, B.merkle, 32) && B.witness == 2 && B.reason && !strcmp(B.reason, "bad-witness-merkle-match")); }
    printf("\n%d passed, %d failed\n", pass_n, fail_n); return fail_n ? 1 : 0;
}
